config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "users/registrations" }
  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show, :edit, :update]
  # resources :discussions
  resources :companies, only: [:show, :new, :create] do
    resources :users, only: [:show]
  end

  resources :projects, only: [:index, :show] do
    get '/dashboard' => 'dashboard#show', as: :user_dashboard
    post '/dashboard/message' => 'dashboard#message'
    patch '/dashboard/agreed' => 'dashboard#agreed'
    resources :roles, only: [:index, :show]
  end

  namespace :cview do
    resources :discussions, param: :project_id do
      post '/roles/:role_id/model/:id' => 'model#create', as: :role_model_create
      patch '/roles/:role_id/model/:id/accept' => 'model#accept', as: :role_model_accept
      resources :list_role, only: [:index]
      resources :roles, only: [:path] do
        resources :list_model, only: [:index]
      end
    end

    resources :roles, only: [] do
      resources :model, only: [:show]
    end

    resources :companies, only: [:show, :edit, :update, :destroy]
    resources :projects do
      patch 'roles/:role_id/update_filter' => 'roles#update_filter', as: :roles_update_filter
      resources :roles do
        resources :models, except: [:index, :destroy]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :projects

  has_many :review_projects, through: :projects, dependent: :destroy
  has_many :discussions, through: :projects
  has_many :roles, through: :projects
  has_many :models, through: :roles

  validates :name, uniqueness: true, presence: true

  has_attachments :photos, maximum: 1
  accepts_nested_attributes_for :users
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/filter_model.rb
class FilterModel < ApplicationRecord
  belongs_to :role
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :project
  belongs_to :role
  belongs_to :user
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :role
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
  has_many :discussions
  has_many :review_projects
  has_many :roles
  has_many :models
  has_many :users, through: :review_projects
  has_many :users, through: :discussions
  has_many :role_skills, through: :roles
  geocoded_by :city
  after_validation :geocode, if: :city_changed?

  validates :name, presence: true
  validates :description, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true

  has_attachments :photos, maximum: 10
end

app/models/review_project.rb
class ReviewProject < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/review_user.rb
class ReviewUser < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :project
  has_many :models
  has_many :filter_models
  has_many :users, through: :models
  has_many :role_skills, dependent: :destroy
  has_many :skills, through: :role_skills

  validates :name, presence: true
  validates :description, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
  validates :hours, presence: true
  validates :income, presence: true
end

app/models/role_skill.rb
class RoleSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :role
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :role_skills
  has_many :users, through: :user_skills
  has_many :roles, through: :role_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  # after_create :send_welcome_email

  geocoded_by :city
  after_validation :geocode, if: :city_changed?

  has_many :companies
  has_many :messages
  has_many :discussions
  has_many :review_users
  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skill
  has_many :models
  has_many :roles, through: :models
  has_many :projects, through: :roles
  has_many :projects, through: :discussions

  validates :username, uniqueness: true, presence: true
  accepts_nested_attributes_for :companies
  has_attachments :photos, maximum: 10

  private

  # include AlgoliaSearch

  # algoliasearch do
  #   attribute :city, :gender, :date_of_birth, :ethnicity, :hair_color, :haircut, :height, :corpulence
  # end


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :user
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: :show

  def index
  end

  def show
  end

  private

  def set_role
    @role = Role.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url
    request.path_info
  end

  def avatar_path(user)
    if user.respond_to?(:facebook_picture_url) && user.facebook_picture_url != nil
      image_path facebook_picture_url
    elsif user.photos.first != nil
      cl_image_path user.photos.first.path
    else
      image_path 'avatar.png'
    end
  end
end

app/views/pages/svg/_cook.html.erb
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve"><g><path d="M46.82,40.936L39,39.198V38v-1.273c3.022-2.181,5-5.723,5-9.727v-4h1v-6h-1v-2.071c3.388-0.487,6-3.408,6-6.929   c0-3.86-3.141-7-7-7c-2.152,0-4.184,1.011-5.5,2.689C36.184,2.011,34.152,1,32,1s-4.184,1.011-5.5,2.689   C25.184,2.011,23.152,1,21,1c-3.859,0-7,3.14-7,7c0,3.521,2.612,6.442,6,6.929V17h-1v6h1v4c0,4.004,1.978,7.546,5,9.727V38v1.198   l-7.82,1.737C11.186,42.268,7,47.485,7,53.626V63h50v-9.374C57,47.485,52.814,42.268,46.82,40.936z M21,19h22v2H21V19z M21,13   c-2.757,0-5-2.243-5-5s2.243-5,5-5c1.769,0,3.423,0.958,4.317,2.501L25.606,6h1.787l0.289-0.499C28.577,3.958,30.231,3,32,3   s3.423,0.958,4.317,2.501L36.606,6h1.787l0.289-0.499C39.577,3.958,41.231,3,43,3c2.757,0,5,2.243,5,5s-2.243,5-5,5h-1v4H22v-4H21z    M22,27v-4h20v4c0,5.514-4.486,10-10,10S22,32.514,22,27z M27,37.895C28.524,38.597,30.214,39,32,39s3.476-0.403,5-1.105V38v1h-1   c-1.654,0-3,1.346-3,3h-2c0-1.654-1.346-3-3-3h-1v-1V37.895z M9,53.626c0-5.195,3.542-9.611,8.613-10.737L26.108,41H28   c0.552,0,1,0.448,1,1v2h2v2.323l-10,4V61h-2v-4h-2v4H9V53.626z M55,61h-8v-4h-2v4H23v-9.323l10-4V44h2v-2c0-0.552,0.448-1,1-1   h1.892l8.495,1.889C51.458,44.015,55,48.431,55,53.626V61z"></path><circle cx="26" cy="54" r="1"></circle><circle cx="26" cy="58" r="1"></circle></g></svg>

app/views/pages/svg/_dany.html.erb
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve"><g><path d="M46.82,40.936L39,39.198v-2.471c2.638-1.904,4.472-4.847,4.896-8.228C45.894,26.4,47,23.666,47,20.757v-7.111   c1.813-1.305,3-3.427,3-5.826c0-2.737-1.521-5.198-3.969-6.422L44,0.382v2.952C44,4.252,43.252,5,42.333,5   c-0.522,0-1.02-0.249-1.335-0.669L40.899,4.2C39.397,2.196,37.005,1,34.5,1H28c-6.065,0-11,4.935-11,11v8.757   c0,2.908,1.106,5.642,3.104,7.741c0.424,3.382,2.258,6.324,4.896,8.228v2.471l-7.82,1.738C11.186,42.268,7,47.486,7,53.626V63h19   h12h19v-9.374C57,47.486,52.814,42.268,46.82,40.936z M37.356,51H29v-2h-2v2h-0.356l-4.177-9.19l1.713-0.381   C24.823,44.049,27.185,46,30,46h4c2.815,0,5.177-1.951,5.821-4.571l1.713,0.381L37.356,51z M45,20.757c0,1.477-0.35,2.897-1,4.176   V14.894c0.341-0.057,0.677-0.132,1-0.235V20.757z M19,12c0-4.962,4.037-9,9-9h6.5c1.879,0,3.673,0.897,4.802,2.402l0.098,0.13   C40.088,6.451,41.185,7,42.333,7c1.894,0,3.457-1.443,3.647-3.287C47.245,4.681,48,6.182,48,7.82c0,2.856-2.324,5.18-5.181,5.18H24   c-2.206,0-4,1.794-4,4v1v6.933c-0.65-1.279-1-2.7-1-4.176V12z M22,27v-9v-1c0-1.103,0.897-2,2-2h18v12c0,5.514-4.486,10-10,10   S22,32.514,22,27z M32,39c1.786,0,3.476-0.403,5-1.105v2.908l0.86,0.191C37.415,42.717,35.861,44,34,44h-4   c-1.861,0-3.415-1.283-3.86-3.007L27,40.802v-2.908C28.524,38.597,30.214,39,32,39z M19,61v-4h-2v4H9v-7.374   c0-5.195,3.542-9.611,8.613-10.738l2.858-0.635l4.208,9.257C24.266,51.877,24,52.405,24,53v8H19z M32,61h-6v-8h6h6l0.001,8H32z    M55,61h-8v-4h-2v4h-5v-8c0-0.595-0.266-1.123-0.679-1.49l4.208-9.257l2.858,0.635C51.458,44.015,55,48.431,55,53.626V61z"></path><path d="M36,57c0-2.206-1.794-4-4-4s-4,1.794-4,4s1.794,4,4,4S36,59.206,36,57z M32,59c-1.103,0-2-0.897-2-2s0.897-2,2-2   s2,0.897,2,2S33.103,59,32,59z"></path></g></svg>

app/views/pages/svg/_neutral.html.erb
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve"><g><path d="M46.82,40.936L39,39.198v-2.471c3.022-2.181,5-5.723,5-9.727v-0.648l1.371-1.714C47.066,22.519,48,19.856,48,17.142V17   c0-8.822-7.178-16-16-16S16,8.178,16,17v0.142c0,2.715,0.934,5.377,2.629,7.496L20,26.352V27c0,4.004,1.978,7.546,5,9.727v2.471   l-7.82,1.737C11.186,42.268,7,47.485,7,53.626V63h50v-9.374C57,47.485,52.814,42.268,46.82,40.936z M41.287,41.755l2.283,3.804   l-9.973,4.603l4.922-9.023L41.287,41.755z M18,17.142V17c0-7.72,6.28-14,14-14s14,6.28,14,14v0.142c0,2.154-0.713,4.263-2,5.985   v-8.259l-6.147,0.769c-3.865,0.482-7.84,0.482-11.705,0L20,14.867v8.259C18.713,21.405,18,19.296,18,17.142z M22,27v-9.867   l3.899,0.487c4.027,0.504,8.174,0.504,12.201,0L42,17.133V27c0,5.514-4.486,10-10,10S22,32.514,22,27z M32,39   c1.786,0,3.476-0.403,5-1.105v1.851l-5,9.167l-5-9.167v-1.851C28.524,38.597,30.214,39,32,39z M25.482,41.139l4.922,9.023   l-9.973-4.603l2.283-3.804L25.482,41.139z M55,61h-8v-4h-2v4H32H19v-4h-2v4H9v-7.374c0-5.195,3.542-9.611,8.613-10.737l2.409-0.536   l-2.453,4.088L32,53.102l14.431-6.66l-2.453-4.088l2.409,0.536C51.458,44.015,55,48.431,55,53.626V61z"></path><circle cx="32" cy="56" r="1"></circle><circle cx="32" cy="60" r="1"></circle></g></svg>

app/views/pages/svg/_shirtguy.html.erb
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve"><path d="M46.82,40.936L39,39.198v-2.471c2.918-2.106,4.85-5.485,4.979-9.32C46.568,24.675,48,21.123,48,17.343V13  c0-2.533-1.893-4.632-4.339-4.957C41.564,3.745,37.203,1,32.384,1h-1.683c-3.253,0-6.458,1.1-9.026,3.097  C18.068,6.902,16,11.132,16,15.701v1.643c0,3.779,1.432,7.332,4.021,10.064c0.13,3.835,2.061,7.214,4.979,9.32v2.471l-7.82,1.737  C11.186,42.268,7,47.485,7,53.626V63h20.913h8.174H57v-9.374C57,47.485,52.814,42.268,46.82,40.936z M39.877,41.441l-1.526,6.866  l-4.716-3.368l4.628-3.857L39.877,41.441z M18,15.701c0-3.947,1.787-7.601,4.903-10.025C25.121,3.95,27.891,3,30.701,3h1.683  c4.226,0,8.032,2.51,9.697,6.394L42.341,10H43c1.654,0,3,1.346,3,3v4.343c0,2.457-0.703,4.802-2,6.82V16h-1.395  c-1.923,0-3.707-0.955-4.773-2.555L37.535,13h-2.102l-0.291,0.485C33.472,16.27,30.416,18,27.169,18H20v6.163  c-1.297-2.018-2-4.363-2-6.82V15.701z M22,27v-7h5.169c3.736,0,7.264-1.885,9.352-4.958c1.337,1.705,3.319,2.767,5.479,2.935V27  c0,5.514-4.486,10-10,10S22,32.514,22,27z M32,39c1.786,0,3.476-0.403,5-1.105v1.636l-5,4.167l-5-4.167v-1.636  C28.524,38.597,30.214,39,32,39z M25.736,41.083l4.628,3.857l-4.716,3.368l-1.526-6.866L25.736,41.083z M19,61v-4h-2v4H9v-7.374  c0-5.195,3.542-9.611,8.613-10.737l4.557-1.013l2.182,9.817l3.457-2.47l1.156,1.156L28.08,61H19z M30.087,61l0.948-11.379  l-1.577-1.577L32,46.229l2.542,1.816l-1.577,1.577L33.913,61H30.087z M55,61h-8v-4h-2v4h-9.08l-0.885-10.621l1.156-1.156l3.457,2.47  l2.182-9.817l4.557,1.013C51.458,44.015,55,48.431,55,53.626V61z"></path></svg>

app/views/shared/_add_button.html.erb
<svg fill="#B9DE50" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="-255 347 100 100" style="enable-background:new -255 347 100 100;" xml:space="preserve"><path d="M-187.2,352.7c-5.5-2.2-11.5-3.4-17.8-3.4c-24.3,0-44.4,18.2-47.3,41.8c-0.2,1.9-0.4,3.9-0.4,5.9  c0,26.3,21.4,47.7,47.7,47.7c26.3,0,47.7-21.3,47.7-47.7C-157.3,376.9-169.7,359.8-187.2,352.7z M-184.3,398.9h-18.8v18.8  c0,1-0.8,1.9-1.9,1.9c-1,0-1.9-0.8-1.9-1.9v-18.8h-18.8c-1,0-1.9-0.8-1.9-1.9s0.8-1.9,1.9-1.9h18.8v-18.8c0-1,0.8-1.9,1.9-1.9  c1,0,1.9,0.8,1.9,1.9v18.8h18.8c1,0,1.9,0.8,1.9,1.9S-183.3,398.9-184.3,398.9z"></path></svg>

app/views/shared/_check_button.html.erb
<svg fill="#B9DE50" xmlns:x="http://ns.adobe.com/Extensibility/1.0/" xmlns:i="http://ns.adobe.com/AdobeIllustrator/10.0/" xmlns:graph="http://ns.adobe.com/Graphs/1.0/" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="-949 951 100 100" style="enable-background:new -949 951 100 100;" xml:space="preserve"><switch><foreignObject requiredExtensions="http://ns.adobe.com/AdobeIllustrator/10.0/" x="0" y="0" width="1" height="1"></foreignObject><g i:extraneous="self"><path d="M-899,953.5c-26.2,0-47.5,21.3-47.5,47.5s21.3,47.5,47.5,47.5s47.5-21.3,47.5-47.5S-872.8,953.5-899,953.5z M-871.4,991.2    l-30.5,30.5c-0.7,0.7-1.6,1.1-2.5,1.1c-0.9,0-1.8-0.4-2.5-1.1l-16.8-16.8c-1.4-1.4-1.4-3.7,0-5.1c1.4-1.4,3.7-1.4,5.1,0l14.2,14.2    l28-28c1.4-1.4,3.7-1.4,5.1,0C-870,987.5-870,989.8-871.4,991.2z"></path></g></switch></svg>

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>

 <script type="text/javascript">

     <% resource.errors.full_messages.each do |msg| %>

               toastr.error('<%= msg %>')

     <% end %>

 </script>

 <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_mail.html.erb
<svg fill="#D7D7D7" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve"><path d="M68.582,34.815H31.419c-1.34,0-2.43,1.09-2.43,2.429v25.51c0,1.34,1.09,2.43,2.43,2.43h37.163  c1.338,0,2.428-1.09,2.428-2.43v-25.51C71.01,35.905,69.92,34.815,68.582,34.815z M68.043,60.308  c0.402,0.378,0.422,1.011,0.045,1.414c-0.197,0.209-0.463,0.315-0.73,0.315c-0.244,0-0.49-0.09-0.684-0.271l-10.838-10.17  l-4.803,4.684c-0.195,0.189-0.447,0.284-0.699,0.284c-0.246,0-0.492-0.09-0.685-0.271l-5.458-5.123L33.341,61.753  c-0.194,0.189-0.446,0.284-0.698,0.284c-0.26,0-0.52-0.101-0.716-0.302c-0.386-0.396-0.378-1.028,0.018-1.414l10.787-10.521  L31.958,39.69c-0.402-0.378-0.423-1.011-0.045-1.414s1.01-0.422,1.414-0.045l16.993,15.949L66.66,38.245  c0.395-0.385,1.027-0.378,1.414,0.018c0.385,0.396,0.377,1.028-0.018,1.414L57.27,50.198L68.043,60.308z M50,11.297  c-21.375,0-38.703,17.328-38.703,38.703S28.625,88.703,50,88.703c21.375,0,38.704-17.328,38.704-38.703S71.375,11.297,50,11.297z   M73.01,62.754c0,2.442-1.986,4.43-4.428,4.43H31.419c-2.442,0-4.43-1.987-4.43-4.43v-25.51c0-2.442,1.987-4.429,4.43-4.429h37.163  c2.441,0,4.428,1.986,4.428,4.429V62.754z"></path></svg>

app/views/shared/_message.html.erb
<% unless flash.empty? %>

       <script type="text/javascript">

       <% flash.each do |f| %>

        <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>

         toastr['<%= type %>']('<%= f[1] %>')

       <% end %>

       </script>

<% end %>

app/views/shared/_navbar.html.erb
<div id="navbar">
  <div class="navbar-wagon <%= yield(:navbar_class) %>">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "castors.png" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <% if user_signed_in? %>
        <!-- Links when logged in -->
        <% if url.exclude?('cview')%>
          <%= link_to "Projects", projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "My profile", profile_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
        <% else %>
          <!-- Links when logged in and with 'cview' in url -->
          <% unless current_user.company_id.blank? %>
            <%= link_to "Projects", cview_projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
          <%= link_to "Discussions", cview_discussions_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "My company", cview_company_path(current_user.company_id), class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>

        <!-- Avatar with dropdown menu (All)-->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <!-- No agency -->
            <% if url.exclude?('cview')%>
              <%= image_tag avatar_path(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <% unless current_user.company_id.blank? %>
                <li>
                  <%= link_to "Agency", cview_projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
                </li>
                <% end %>
            <% else %>
            <!-- for agency -->
              <%= image_tag avatar_path(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li>
                  <%= link_to "My account", projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
                </li>
            <% end %>
              <li>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Agency", new_company_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <!-- No agency menu -->
          <% if url.exclude?('cview')%>
            <li><%= link_to "Projects", projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li><%= link_to "My profile", profile_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <% unless current_user.company_id.blank? %>
              <li>
                <%= link_to "Agency", cview_projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
              </li>
            <% end %>
          <% else %>
            <!-- (Company view) Links when logged in and with 'cview' in url -->
            <% unless current_user.company_id.blank? %>
              <li>
                <%= link_to "Projects", cview_projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
              </li>
              <li>
                <%= link_to "Discussions", cview_discussions_path, class: "navbar-wagon-item navbar-wagon-link" %>
              </li>
              <li>
                <%= link_to "My company", cview_company_path(current_user.company_id), class: "navbar-wagon-item navbar-wagon-link" %>
              </li>
              <li>
                <%= link_to "My account", projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
              </li>
            <% end %>
          <% end %>
          <li>
            <%= link_to edit_user_registration_path do %>
             <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Agency", new_company_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        </ul>
      </div>
    </div>
    <% end %>
  </div>
</div>