config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "users/registrations" }
  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show, :edit, :update]
  # resources :discussions
  resources :companies, only: [:show, :new, :create] do
    resources :users, only: [:show]
  end

  resources :projects, only: [:index, :show] do
    get '/dashboard' => 'dashboard#show', as: :user_dashboard
    post '/dashboard/message' => 'dashboard#message'
    patch '/dashboard/agreed' => 'dashboard#agreed'
    resources :roles, only: [:index, :show]
  end

  namespace :cview do
    resources :discussions, param: :project_id do
      post '/roles/:role_id/model/:id' => 'model#create', as: :role_model_create
      patch '/roles/:role_id/model/:id/accept' => 'model#accept', as: :role_model_accept
      resources :list_role, only: [:index]
      resources :roles, only: [:path] do
        resources :list_model, only: [:index]
      end
    end

    resources :roles, only: [] do
      resources :model, only: [:show]
    end

    resources :companies, only: [:show, :edit, :update, :destroy]
    resources :projects do
      patch 'roles/:role_id/update_filter' => 'roles#update_filter', as: :roles_update_filter
      resources :roles do
        resources :models, except: [:index, :destroy]
      end
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :project
  has_many :models
  has_many :filter_models
  has_many :users, through: :models
  has_many :role_skills, dependent: :destroy
  has_many :skills, through: :role_skills

  validates :name, presence: true
  validates :description, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
  validates :hours, presence: true
  validates :income, presence: true
end

app/controllers/cview/companies_controller.rb
class Cview::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :destroy, :edit, :update]
  before_action :require_legal_representative

  def show
    @legal_representatives = User.where(company_id: @company.id)
  end

  def update
    current_user.update_attributes(user_params[:users_attributes]['0'])
    if @company.update_attributes(company_params)
      redirect_to company_path(@company)
    else
      redirect_to edit_cview_company_path(@company)
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:company).permit(users_attributes: [:first_name, :last_name, :grade_company, :phone_number_pro, :email_pro, :description_pro])
  end

  def company_params
    params.require(:company).permit(:name, :country, :description, :address, :phone_numer, :email, :website, photos: [])
  end

  def require_legal_representative
    unless @company.id == current_user.company_id
      redirect_to projects_path
    end
   # @legal_representative = current_user
  end

  def set_company
    # @company = Company.find(params[:id])
    @company = Company.find(current_user.company_id)
  end
end

app/controllers/cview/discussions_controller.rb
class Cview::DiscussionsController < ApplicationController
  before_action :require_legal_representative
  before_action :set_project, only: :show
  before_action :set_discussion, only: :show

  def index
    @projects = Project.where(company_id: current_user.company_id)
  end

  def show
    @roles = Role.where(project: @project)
  end

  def new
    @discussion = Discussion.new
  end

  # def create
  #   @discussion = Discussion.new(discussion_params)
  #   if @projec.save
  #     redirect_to cview_project_path(@project)
  #   else
  #     render :new
  #   end
  # end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def discussion_params
    params.require(:discussion).permit(:name)
  end

  def require_legal_representative
    unless Company.exists?(id: current_user.company_id)
      redirect_to projects_path
    end
  #  @legal_representative = current_user
  end

  def set_project
    @project = Project.where(id: params[:project_id], company_id: current_user.company_id)
  end

  def set_discussion
    @discussion = Discussion.where(project: @project).first
  end

end

app/controllers/cview/list_model_controller.rb
class Cview::ListModelController < ApplicationController
  before_action :require_legal_representative
  before_action :set_project, only: :index
  before_action :set_discussion, only: :index
  before_action :set_role, only: :index

  def index
    @models = Model.where(project: @project, role: @role)
    @discussions = []
    @models.each { |m|
      discussion = Discussion.where(project: @project, user: m.user)[0]
      if discussion != nil
        user = m.user
        last_message = Message.where(discussion_id: discussion.discussion_id).select(:id, :user_id, :content, :created_at).last
        last_message_user = last_message.user.username
        response = last_message.user.username == current_user.username ? false : true
        @discussions << {
          discussion: discussion,
          user: user,
          last_message_user: last_message_user,
          last_message: last_message,
          response: response
        }
      end
    }
  end

  private

  def require_legal_representative
    unless Company.exists?(id: current_user.company_id)
      redirect_to projects_path
    end
   # @legal_representative = current_user
  end

  def set_project
    @project = Project.where(id: params[:discussion_project_id], company_id: current_user.company_id)
  end

  def set_discussion
    @discussion = Discussion.where(project: @project).first
  end

  def set_role
    @role = Role.find(params[:role_id])
  end
end

app/controllers/cview/model_controller.rb
class Cview::ModelController < ApplicationController
  before_action :require_legal_representative
  before_action :set_role, only: [:show, :create, :accept]
  before_action :set_project, only: [:show, :create, :accept]
  before_action :set_model, only: [:show, :create, :accept]
  before_action :set_discussion, only: [:show, :create]


  def show
    @messages = Message.where(discussion_id: @discussion.discussion_id)
    @message = Message.new
  end

  def create
    @message = Message.new(content: message_params[:content], discussion_id: @discussion.discussion_id, user:current_user)
    if @message.save
      redirect_to cview_role_model_path(@role, params[:id])
    else
      @messages = Message.where(discussion_id: @discussion.discussion_id)
      render :show
    end
  end

  def accept
    if @agreed
      @role.update_attributes(selected_user_id: @model.id)
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def require_legal_representative
    unless Company.exists?(id: current_user.company_id)
      redirect_to projects_path
    end
  #  @legal_representative = current_user
  end

  def set_model
    @model = User.find(params[:id])
    @agreed = Model.where(project: @project, user: @model).first.agreed
  end

  def set_role
    @role = Role.find(params[:role_id])
  end

  def set_project
    # @project = Project.find(params[:discussion_project_id])
    @project = Project.find(@role.project_id)
  end

  def set_discussion
    @discussion = Discussion.where(project: @project, user: @model)[0]
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/cview/models_controller.rb
class Cview::ModelsController < ApplicationController
  before_action :require_legal_representative
  before_action :set_role, only: [:index]
  before_action :set_user, only: [:create]
  before_action :get_role, only: [:create, :update]
  before_action :set_project, only: [:index, :create, :update]

  def index
    vals = {gender: @role.gender, ethnicity: @role.ethnicity, hair_color: @role.hair_color, haircut: @role.haircut, height: @role.height, weight: @role.weight, corpulence: @role.corpulence}
    #vals.reject!{ |key, value| value.nil? }
    vals.reject!{ |key, value| value.nil? }
    # @users = User.search(vals, hitsPerPage: 2)
    @users = User.where(vals)
  end

  def create
    @model = Model.new(project: @project, role: @role, user: @user, checked: true)
    @model.save!
    @discussion_id = "#{@project.company.name} #{@project.name} #{@user.username}".gsub(/\W/,'-')
    @discussion = Discussion.new(name: "#{@project.name}", discussion_id: @discussion_id, user_id: current_user.id, project_id: @project.id)
    @discussion.save!
    @discussion = Discussion.new(name: "#{@project.name}", discussion_id: @discussion_id, user_id: @user.id, project_id: @project.id)
    @discussion.save!
    @message = Message.new(content: "Hi #{@user.username}, we want you !", discussion_id: @discussion_id, user_id: current_user.id)
    @message.save!
    redirect_back(fallback_location: root_path)
  end

  def update
    @model = Model.where(role_id: params[:role_id], user_id: params[:id])[0]
    @model.toggle(:checked)
    @model.save
    redirect_back(fallback_location: root_path)
    #redirect_to cview_project_role_path(project_id: @project, id: @role)
  end

  private

  def require_legal_representative
    unless Company.exists?(id: current_user.company_id)
      redirect_to projects_path
    end
   # @legal_representative = current_user
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_role
    @role = Role.find(params[:id])
  end

  def get_role
    @role = Role.find(params[:role_id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/cview/projects_controller.rb
class Cview::ProjectsController < ApplicationController
  before_action :require_legal_representative
  before_action :set_project, only: :show

  def index
    @projects = Project.where(company_id: current_user.company_id)
  end

  def show
    @roles = Role.where(project: @project)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.company_id = current_user.company_id
    if @project.save
      redirect_to cview_project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def project_params
    params.require('project').permit(:name, :description, :date_start, :date_end, :city, :country, photos: [])
  end

  def require_legal_representative
    unless Company.exists?(id: current_user.company_id)
      redirect_to projects_path
    end
   # @legal_representative = current_user
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/cview/roles_controller.rb
class Cview::RolesController < ApplicationController
  before_action :require_legal_representative
  before_action :set_role, only: [:show, :edit, :update]
  before_action :get_role, only: [:update_filter]
  before_action :set_project, only: [:show, :create, :edit, :update, :update_filter]
  before_action :set_filter_models, only: [:show, :update_filter]

  def index
    @roles = Role.where(company_id: @legal_representative.company_id)
  end

  def show
    if params[:discussion_id]
      redirect_to root_path
    else
      vals = {}
          unless @filter_models.gender.include?("all")
            vals[:gender] = @filter_models.gender
          end
          unless @filter_models.ethnicity.include?("all")
            vals[:ethnicity] =  @filter_models.ethnicity
          end
          unless @filter_models.hair_color.include?("all")
            vals[:hair_color] =  @filter_models.hair_color
          end
          unless @filter_models.haircut.include?("all")
            vals[:haircut] =  @filter_models.haircut
          end
          unless @filter_models.height == []
            vals[:height] =  @filter_models.height
          end
          unless @filter_models.corpulence.include?("all")
            vals[:corpulence] =  @filter_models.corpulence
          end
      @users = User.where(vals)
      @models = Model.where(role: @role).select(:user_id, :checked)
    end
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @role.project = @project
    @filter_models = @role.filter_models.build()
    if @role.save
      @filter_models.update_attributes(filter_models_params)
      redirect_to cview_project_path(@project)
    else
      render :new
    end
  end

  def edit
  end


  def update
    @role.update_attributes(role_params)
    redirect_to cview_project_path(@project)
  end

  def update_filter
    @filter_models.update_attributes(filter_models_update_params)
    redirect_to cview_project_role_path(@project, @role)
  end

  def destroy
  end

  private

  def role_params
    params.require(:role).permit(:name, :description, :date_start, :date_end, :income, :hours, :gender, :ethnicity, :skin_color, :hair_color, :haircut, :height, :weight, :corpulence, photos: [])
  end

  def filter_models_params
    filter = params.require(:role).permit(:gender, :ethnicity, :hair_color, :haircut, :height, :corpulence)
    filter.to_h.transform_values {|v| v.blank? ? [] : Array(v)}
  end

  def filter_models_update_params
    params.require(:filter_model).permit(gender: [], ethnicity: [], hair_color: [], haircut: [], height: [], corpulence: [])
  end

  def require_legal_representative
    unless Company.exists?(id: current_user.company_id)
      redirect_to projects_path
    end
  #  @legal_representative = current_user
  end

  def set_role
    @role = Role.find(params[:id])
  end

  def get_role
    @role = Role.find(params[:role_id])
  end

  def set_project
    if params[:discussion_id]
      @project = Project.find(params[:id])
    else
      @project = Project.find(params[:project_id])
    end
  end

  def set_filter_models
    @filter_models = FilterModel.where(role: @role)[0]
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: :show

  def index
  end

  def show
  end

  private

  def set_role
    @role = Role.find(params[:id])
  end
end

app/views/cview/roles/_form.html.erb
<%= f.input :name, required: false %>
<%= f.input :description, required: false %>
<!-- <label class="control-label" for="date_start">Date start</label>
<input class="form-control" id="date_start" name="date_start" placeholder="" type="text" data-date-format='dd MM, yyyy' />
<label class="control-label" for="date_end">Date end</label>
<input class="form-control" id="date_end" name="date_end" placeholder="" type="text" data-date-format='dd MM, yyyy' /> -->
<%= f.input :date_start, required: false, as: :string, input_html: { class: 'datepicker' } %>
<%= f.input :date_end, required: false, as: :string, input_html: { class: 'datepicker' } %>
<%= f.input :income, required: false %>
<%= f.input :hours, required: false %>

<%= f.input :gender, :item_wrapper_class => 'radio-inline', :collection => ["male", "female", "other"], :as => :radio_buttons %>
<%= f.input :ethnicity, :item_wrapper_class => 'radio-inline', :collection => ["european", "african", "asian", "other"], :as => :radio_buttons %>
<%= f.input :hair_color, :item_wrapper_class => 'radio-inline', :collection => ["black", "brown", "blond", "red", "grey", "white", "other"], :as => :radio_buttons %>
<%= f.input :haircut, :item_wrapper_class => 'radio-inline', :collection => ["bald", "short", "mid-length", "long"], :as => :radio_buttons %>
<%= f.input :corpulence, :item_wrapper_class => 'radio-inline', :collection => ["light-weight", "regular", "heavy-weight", "athletic"], :as => :radio_buttons %>
<br>
<center><%= f.button :submit %></center>

app/views/cview/roles/_show.html.erb
<div class="role" data-role-id="<%= role.id %>" style="display: none;">

    <% if role.selected_user_id? %>
      <div class="avatar-large">
        <% s_user = User.find(role[:selected_user_id]) %>
        <%= image_tag avatar_path(s_user), class: "avatar-large" %>
      </div>
    <% else %>
      <div class="avatar-large">
        <%= render 'unknown' %>
      </div>
    <% end %>


    <div class="role-name">
      <h3><%= role.name %></h3>
      <p>Hours : <%= role.hours.to_i %> <br>
      Salary : <%= role.income %> € </p>
    </div>
    <div class="role-body">
      <p><strong>From <%= role.date_start.strftime("%d.%m.%y") %> to <%= role.date_end.strftime("%d.%m.%y") %></strong></p>
      <p>
        <%= role.description %>
      </p>
      <p> <strong> Specificities : </strong>
        <% if role.gender && role.gender != "" %>
          Gender : <%= role.gender %> |
        <% end %>
        <% if role.ethnicity && role.ethnicity != "" %>
          Ethnicity : <%= role.ethnicity %> |
        <% end %>
        <% if role.hair_color && role.hair_color != "" %>
          Hair color : <%= role.hair_color %> |
        <% end %>
        <% if role.haircut && role.haircut != "" %>
          Haircut : <%= role.haircut %> |
        <% end %>
        <% if role.height && role.height!= ""  %>
          Height : <%= role.height %> |
        <% end %>
        <% if role.corpulence && role.corpulence != ""  %>
          Body type : <%= role.corpulence %>
        <% end %>
      </p>
    </div>
    <div class="role-status">

      <% if role.selected_user_id? %>
        <%= link_to 'Messages', cview_role_model_path(role_id: role.id, id: role.selected_user_id), class: "role-controls"%>
      <% else %>
        <%= link_to 'Browse models', cview_project_role_path(project_id: @project.id, id: role.id), class: "role-controls"%>
      <% end %>


      <%= link_to 'Edit role', edit_cview_project_role_path(project_id: @project.id, id: role.id), class: "role-controls"%> <br>
    </div>

</div>

app/views/cview/roles/_unknown.html.erb
<svg fill="#D7D7D7" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="-255 347 100 100" style="enable-background:new -255 347 100 100;" xml:space="preserve"><path d="M-205,394c5.1,0,9.2-5.3,9.2-11.8c0-6-3.7-10.1-9.2-10.1c-5.5,0-9.2,4.1-9.2,10.1C-214.2,388.7-210.1,394-205,394z   M-186.8,351.8c-5.6-2.3-11.7-3.5-18.2-3.5c-24.8,0-45.3,18.6-48.3,42.6c-0.2,2-0.4,4-0.4,6.1c0,26.9,21.8,48.7,48.7,48.7  c26.9,0,48.7-21.8,48.7-48.7C-156.3,376.5-168.9,359-186.8,351.8z M-205,368.3c7.7,0,13,5.7,13,13.9c0,8.6-5.8,15.6-13,15.6  c-7.2,0-13-7-13-15.6C-218,374-212.7,368.3-205,368.3z M-183.6,423.9L-183.6,423.9c-1.1,0-1.9-0.8-1.9-1.9c0-2.1-0.1-3.9-0.1-4.2  c-1.2-11.3-14-12.6-19.4-12.6c-6.4,0-17.4,1.5-19.2,11.5c-0.2,0.9-0.3,3-0.3,4.1c0,1-0.8,1.9-1.9,1.9c-1,0-1.9-0.8-1.9-1.9  c0-1,0.1-3.5,0.3-4.7c1.7-9.3,10-14.6,23-14.6c13.4,0,22.1,6,23.2,16c0.1,0.5,0.1,3.1,0.1,4.6C-181.7,423-182.5,423.9-183.6,423.9z"></path></svg>

app/views/cview/roles/edit.html.erb
<div class="back_login" style="bottom: 0px">
<%=
# image_tag 'cardbackground.jpg'
%>
</div>
<div class="containerr" style="width: 100%; margin-top: 50px">
<div class="col-sm-12 col-md-6">
<h1>Edit the role</h1>
</div>
<div class="col-sm-12 col-md-6">
<div class="formm">
  <%= simple_form_for @role, url: cview_project_role_path(@project, @role) do |f| %>
  <%= render 'cview/roles/form', f: f %>
  <% end %>
</div>
</div>
</div>

app/views/cview/roles/new.html.erb
<div id="new_role">
  <div class="back_login" style="bottom: 0px">
  <%=
  # image_tag 'cardbackground.jpg'
  %>
  </div>
  <div class="containerr" style="width: 100%; margin-top: 50px">
  <div class="col-sm-12 col-md-6">
    <h1>Add a new role</h1>
    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
  </div>
  <div class="col-sm-12 col-md-6">
  <div class="formm">
    <%= simple_form_for @role, url: cview_project_roles_path do |f| %>
    <%= render 'cview/roles/form', f: f %>
    <% end %>
  </div>
  </div>
  </div>
</div>

app/views/cview/roles/show.html.erb
<div class="role-view">
<%= render file: 'cview/models/index' %>
</div>