config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "users/registrations" }
  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show, :edit, :update]
  # resources :discussions
  resources :companies, only: [:show, :new, :create] do
    resources :users, only: [:show]
  end

  resources :projects, only: [:index, :show] do
    get '/dashboard' => 'dashboard#show', as: :user_dashboard
    post '/dashboard/message' => 'dashboard#message'
    patch '/dashboard/agreed' => 'dashboard#agreed'
    resources :roles, only: [:index, :show]
  end

  namespace :cview do
    resources :discussions, param: :project_id do
      post '/roles/:role_id/model/:id' => 'model#create', as: :role_model_create
      patch '/roles/:role_id/model/:id/accept' => 'model#accept', as: :role_model_accept
      resources :list_role, only: [:index]
      resources :roles, only: [:path] do
        resources :list_model, only: [:index]
      end
    end

    resources :roles, only: [] do
      resources :model, only: [:show]
    end

    resources :companies, only: [:show, :edit, :update, :destroy]
    resources :projects do
      patch 'roles/:role_id/update_filter' => 'roles#update_filter', as: :roles_update_filter
      resources :roles do
        resources :models, except: [:index, :destroy]
      end
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :projects

  has_many :review_projects, through: :projects, dependent: :destroy
  has_many :discussions, through: :projects
  has_many :roles, through: :projects
  has_many :models, through: :roles

  validates :name, uniqueness: true, presence: true

  has_attachments :photos, maximum: 1
  accepts_nested_attributes_for :users
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def show
    @legal_representatives = User.where(company_id: @company.id)
  end

  def new
    if current_user.company_id.blank?
      @company = Company.new
    else
      redirect_to cview_projects_path
    end
  end

  def create
    @company = Company.new(company_params[:companies_attributes]['0'])
    if @company.save
      current_user.company_id = @company.id
      if current_user.update_attributes(user_params)
        redirect_to cview_company_path(@company)
      else
        render :new
      end
    else
      render :new
    end
  end

  def edit
    @legal_representatives = User.where(company_id: @company.id)
  end

  def update
    @company.update_attributes(company_params)
    redirect_to cview_company_path(@company)
  end

  def destroy
    @company.destroy
    redirect_to projects_path
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :grade_company, :phone_number_pro, :email_pro, :description_pro)
  end

  def company_params
    params.require(:user).permit(companies_attributes: [:name, :country, photos: []])
  end
end

app/controllers/cview/companies_controller.rb
class Cview::CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :destroy, :edit, :update]
  before_action :require_legal_representative

  def show
    @legal_representatives = User.where(company_id: @company.id)
  end

  def update
    current_user.update_attributes(user_params[:users_attributes]['0'])
    if @company.update_attributes(company_params)
      redirect_to company_path(@company)
    else
      redirect_to edit_cview_company_path(@company)
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:company).permit(users_attributes: [:first_name, :last_name, :grade_company, :phone_number_pro, :email_pro, :description_pro])
  end

  def company_params
    params.require(:company).permit(:name, :country, :description, :address, :phone_numer, :email, :website, photos: [])
  end

  def require_legal_representative
    unless @company.id == current_user.company_id
      redirect_to projects_path
    end
   # @legal_representative = current_user
  end

  def set_company
    # @company = Company.find(params[:id])
    @company = Company.find(current_user.company_id)
  end
end

app/views/companies/_form.html.erb
<%= simple_form_for current_user, url: companies_path, method: :post do |u| %>
  <%= u.input :first_name %>
  <%= u.input :last_name %>
  <%= u.input :grade_company %>
  <%= u.input :phone_number_pro %>
  <%= u.input :email_pro, label: 'Email pro' %>
  <%= u.simple_fields_for :companies, @company do |c| %>
    <%= c.input :name, required: false, label: 'Society' %>
    <%= c.input :country %>
    <br>
    <%= c.input :photos, as: :attachinary %>
  <% end %>
  <br>
  <%= u.button :submit, 'Create your Dam'%>
<% end %>

app/views/companies/index.html.erb
<h1>Companies#index</h1>
<p>Find me in app/views/companies/index.html.erb</p>

app/views/companies/new.html.erb
<div class="back_login" style="bottom: 0px">
<%=
# image_tag 'cardbackground.jpg'
%>
</div>
<div class="containerr" style="width: 100%; margin-top: 50px">
<div class="col-sm-12 col-md-6">
<h1>Become a Castor</h1>
</div>
<div class="col-sm-12 col-md-6">
<div class="formm">
<center><%= render 'companies/form' %></center>
</div>
</div>

app/views/companies/show.html.erb
<div id="profil">
  <center><h2>The Dam</h2></center>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <div class="photos">
        <% if @company.photos[0] == nil %>
        <%= image_tag 'defaultcie.jpg', width: 300, height: 200, crop: :fill %>
        <% else %>
        <%= cl_image_tag @company.photos[0].path, width: 300, height: 200, crop: :fill %>
        <% end %>
        <h3><%= @company.name %></h3>
        <c><%= @company.address %>
        <%= @company.country %></c>
        <br></br>
        <c>Phone: <%= @company.phone_number %></c>
      </div>
      </div>
      <div class="backtext">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
          <br></br>
        <b>Contact:</b><br>
        <a><%= @company.email %></a>
        <br><br></br>
        <b>Website:</b><br>
        <a><%= @company.website %></a>
        <br><br></br>
        <b>Description:</b><br>
        <a><%= @company.description %></a>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <br></br>
      </div>
    </div>
    </div>
    <br></br>
    <center><h4>The Castor</h4></center>
    <% @legal_representatives.each do |castor| %>
    <div class="castors">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
          <%= castor.first_name %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
          <%= castor.last_name %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
          <%= castor.grade_company %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>